Added brazilian portuguese translation
nano-wallet-company/nano-wallet-android pull request #24
Opened 2018-07-02 17:38 UTC by guisantos

- Added brazilian portuguese translation.

- Fixed the introduction to legal description, there was a comma misplaced and also that part("If you do not understand or agree to any of the Terms and ) I think the correct is "disagree" and not "agree".

2018-07-02 18:00 UTC, taciosd reviewed
First of all Nice initiative to translate to portuguese speakers.
I volunteer to review the translations. Will post here as soon as possible if no one objects.

2018-07-02 18:43 UTC, taciosd requested changes
Some considerations to Brazillian Portuguese language speakers and to the author:

Obs.: Usei parentese somente para indicar caracteres e espaços a corrigir.

13: Não seria melhor traduzir para: "Endereço da semente"?
15: Sugestão: "Sua semente da carteira nano". Ou talvez ao invés de traduzir Wallet seed para Semente de carteira seria melhor somente "semente", já que fica estranho no portugues e dá a impressão que a semente é algo fixo a esta carteira. Mas claro, fica a seu critério. Não sei se em algum dos casos essa alteração faria algum mal.
16: Correções: "...na (r)ede Nano."; "Nós não temos acess(o) a ela"
17: Sugestão: "Eu compreendo, Continuar"
18: Correção: "...em algum local seguro como..."
27: Correção/typos: "sobre o aplicati(v)o"; "...está sujeito a sua concordância com todos..."; "...todos os Termos e C(o)ndições..."; "Ao marcar as caixas abaixo e..."; "...ou autorizado a us(a)r..."; "...do seu dispositivo."
34-35: Sugestão: Talvez seja melhor usar "Aviso de Log Out" já que a palavra não costuma ser traduzida no português brasileiro.
41: "...ID (d)o seu dispositivo..."; "assim como as m(é)tricas
41: (Sugestão) Como existem questões legais onde a Carteira é endereçada oficialmente como Wallet talvez seja melhor manter a palavra Wallet no original esse e em outros casos.
50: "Senha inválida digitada"
110: "A (quantia) que você digitou (era) maior que seu (saldo) de Nano."; "\n\nNós( )preenchemos o formulário com seu saldo completo..."
114: (typo): "endereço"
124: (typo): "...v(á)lida."
131: (typo): "Cr(í)tico..."
138: "Transferir (saldo)..."
141: "Transferir (saldo)..."
149: "Lembrete da Nova..."

2018-07-02 19:44 UTC, guisantos commented
Thank you @taciosd I agree with some of the changes you've suggested. I'll change them as soon as possible. Is good to have a different perspective.

2018-07-03 00:34 UTC, brunoelyg commented
I am the community manager from Brazil and I am here to thank you, this is so important!

2018-07-03 00:41 UTC, guisantos commented
Thanks Bruno!

2018-07-03 08:26 UTC, PlasmaPower commented on app/src/main/res/values/strings.xml
> +    <string name="intro_legal_description">Your use of this Nano Wallet mobile application is subject to your agreement to all terms and conditions of the End User License Agreement and Privacy Polic
I'd prefer to leave "If you do not understand or agree to" as is. Personally, I interpret the "do not" as applying to both the "understand" and "agree". Normally I'd be fine with this change but I'd prefer not to modify the legal text in general.

2018-07-03 09:13 UTC, rotilho commented
The translation for seed sounds really strange. I'd stick to seed instead of semente; in Brazil we dont usually to translate everything specially tech-related words.

2018-07-03 12:13 UTC, guisantos commented on app/src/main/res/values/strings.xml
> +    <string name="intro_legal_description">Your use of this Nano Wallet mobile application is subject to your agreement to all terms and conditions of the End User License Agreement and Privacy Polic
Ok @PlasmaPower was just a suggestion, thanks for your comment!

2018-07-03 12:16 UTC, guisantos commented
@rotilho I understand your concern, had the same debate with myself when I was translating seed and also with wallet, we know what those things are, but the average people might not understand, that's why I suggested translating them.

2018-07-05 14:01 UTC, guisantos commented
I've changed the "semente" back to seed, and also there was a string untranslated. I'm confident that this version is ready to go live.

2018-07-05 14:03 UTC, guisantos reviewed
I agree with your point.

2018-07-05 14:38 UTC, PlasmaPower commented on app/src/main/res/values/strings.xml
> +    <string name="intro_legal_description">Your use of this Nano Wallet mobile application is subject to your agreement to all terms and conditions of the End User License Agreement and Privacy Polic
Could you revert this change?

2018-07-05 14:55 UTC, merged

2018-07-05 14:55 UTC, PlasmaPower commented
Thanks! I'll make a new release on Google Play shortly.